// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BindingResult = { name: string, outcome: Outcome, 
/**
 * Committed record: catalysts actually invoked. Monotone.
 */
record: number, trace: Array<TraceStep>, };

export type CellBinding = { catalyst: string, cell: string, };

export type ClientMessage = { "type": "hello", token: string, protocol: number, } | { "type": "check", request_id: string, source: string, 
/**
 * Substrate floors, as name → value. Absent floors leave T-Seek-Pos
 * unchecked and produce a warning rather than an error.
 */
floors: Array<FloorBinding>, } | { "type": "run", request_id: string, source: string, floors: Array<FloorBinding>, cells: Array<CellBinding>, } | { "type": "analyse", request_id: string, 
/**
 * A serialised `Tabular` substrate. Opaque to the protocol: the
 * substrate schema belongs to `mekaneck-substrates`, and duplicating
 * it here would be a second source of truth.
 */
substrate: unknown, } | { "type": "ping", request_id: string, };

export type Diagnostic = { message: string, start: number, end: number, line: number, column: number, severity: Severity, };

export type FloorBinding = { substrate: string, value: number, };

export type LawRow = { law: string, estimation: string, 
/**
 * False under instance-specific estimation. A client that renders such a
 * row as a finding is discarding this flag deliberately.
 */
evidential: boolean, max_discrepancy: number, pearson_r: number | null, rmse: number | null, };

/**
 * The two ways an inquiry ends. There is no third, and neither is an error.
 */
export type Outcome = { "outcome": "resolved", cell: string, } | { "outcome": "declined", cells: Array<string>, };

export type ReceiverFloor = { receiver: string, floor: number, estimator: string, 
/**
 * Whether this estimator *could* have returned a non-positive value. A
 * positive floor from a non-falsifiable estimator is not evidence.
 */
falsifiable: boolean, supports_positive_floor: boolean, };

export type SeparationReport = { eta: number, between: number, within: number, n_types: number, n_events: number, 
/**
 * False when a law comparison on this corpus cannot adjudicate the
 * typing, whatever correlation it reports.
 */
informative: boolean, };

export type ServerMessage = { "type": "welcome", protocol: number, server_version: string, 
/**
 * Always loopback. Sent so the UI can state where data is going.
 */
bound_to: string, } | { "type": "denied", reason: string, } | { "type": "diagnostics", request_id: string, diagnostics: Array<Diagnostic>, } | { "type": "run_result", request_id: string, bindings: Array<BindingResult>, } | { "type": "analysis_result", request_id: string, substrate: string, receivers: Array<ReceiverFloor>, cascades: number, separation: SeparationReport, laws: Array<LawRow>, } | { "type": "failed", request_id: string, message: string, } | { "type": "pong", request_id: string, };

export type Severity = "error" | "warning";

export type TraceStep = { catalyst: string, cell: string, record: number, };
