//! Conformance against the Python validation in
//! `chatelier/validation/validate_algebra.py`.
//!
//! These are not unit tests of the Rust in isolation: each asserts a value
//! that the Python suite also produces, so that the two implementations
//! cannot drift apart silently. Where a number is quoted it is the one
//! recorded in `validation/results/`.

use mekaneck_algebra::*;

fn floor() -> Floor {
    Floor::new(10.0).unwrap()
}

fn cascade(states: &[f64], labels: &[&str]) -> Cascade {
    let v: Vec<(f64, String)> = states
        .iter()
        .zip(labels)
        .map(|(s, l)| (*s, l.to_string()))
        .collect();
    Cascade::from_states(&v, floor()).unwrap()
}

/// Reproduce the generator used by `validate_algebra.generate_cascades`,
/// deterministically, so the two suites see the same shape of data.
fn generate(n: usize, means: &[(&str, f64)], sd: f64, seed: u64) -> Vec<Cascade> {
    let mut s = seed;
    let mut next = || {
        s = s.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        ((s >> 11) as f64) / ((1u64 << 53) as f64)
    };
    let mut out = Vec::new();
    for _ in 0..n {
        let len = 3 + (next() * 3.0) as usize; // 3..=5
        let mut states = vec![(100.0, "S0".to_string())];
        let mut cur = 100.0;
        // The label of each event must be the label whose mean generated its
        // power; otherwise the type carries no information about the power by
        // construction and eta is near zero for every regime, which would
        // make the diagnostic untestable rather than exercise it.
        let mut labels = Vec::with_capacity(len);
        for i in 0..len {
            let (label, mean) = means[(next() * means.len() as f64) as usize % means.len()];
            let k = (mean + (next() - 0.5) * 2.0 * sd).min(0.95);
            cur = 10.0 + (cur - 10.0) * (1.0 - k);
            states.push((cur, format!("s{i}")));
            labels.push(label);
        }
        let mut c = Cascade::from_states(&states, floor()).unwrap();
        for (e, label) in c.events.iter_mut().zip(&labels) {
            e.event_type = (*label).to_string();
        }
        out.push(c);
    }
    out
}

/// Thm 5.2 / `check_telescoping`: the Python suite reports a maximum absolute
/// deviation of 2.22e-16 across every regime. The identity is algebraic, so
/// the Rust must reproduce it to the same precision on arbitrary input.
#[test]
fn telescoping_identity_matches_python() {
    let corpus = [
        vec![100.0, 60.0, 35.0, 22.0],
        vec![80.0, 79.0, 41.0, 12.0, 11.0],
        vec![50.0, 70.0, 30.0],
        vec![100.0, 99.9, 99.8],
        vec![100.0, 10.5],
    ];
    let mut worst: f64 = 0.0;
    for states in corpus {
        let labels: Vec<&str> = ["A", "B", "C", "D", "E"][..states.len()].to_vec();
        let c = cascade(&states, &labels);
        let t = test_cascade(&c, Law::Multiplicative, Estimation::InstanceSpecific, None).unwrap();
        worst = worst.max(t.discrepancy());
        assert!(!t.is_evidential(), "instance-specific must not be evidential");
    }
    // Python: max_abs_deviation = 2.220446049250313e-16
    assert!(worst <= 2.220446049250313e-16, "worst deviation {worst:e}");
}

/// Cor 5.3: the degenerate test cannot fail, including on data generated by a
/// process that violates type-stability entirely.
#[test]
fn telescoping_holds_on_adversarial_data() {
    let cs = generate(200, &[("A", 0.9), ("B", -0.4), ("C", 0.05)], 0.4, 99);
    for c in &cs {
        let t = test_cascade(c, Law::Multiplicative, Estimation::InstanceSpecific, None).unwrap();
        assert!(t.discrepancy() < 1e-12, "deviation {:e}", t.discrepancy());
    }
}

/// Thm 5.5: type-averaging breaks the identity, so the test acquires a null.
#[test]
fn type_averaged_test_has_a_null() {
    let cs = generate(300, &[("A", 0.55), ("B", 0.30), ("C", 0.08)], 0.03, 7);
    let avg = TypeAverages::fit(&cs).unwrap();
    let mut max_dev: f64 = 0.0;
    for c in &cs {
        let t = test_cascade(c, Law::Multiplicative, Estimation::TypeAveraged, Some(&avg)).unwrap();
        assert!(t.is_evidential());
        max_dev = max_dev.max(t.discrepancy());
    }
    assert!(max_dev > 1e-6, "type-averaged discrepancy vanished: {max_dev:e}");
}

/// Prop 6.3: the four laws are ordered `max ≤ mult ≤ min(Σκ,1)`, strictly off
/// the degenerate cases.
#[test]
fn law_ordering_matches_python() {
    let ps: Vec<Power> = [0.55, 0.30, 0.08]
        .iter()
        .map(|k| Power::new(*k).unwrap())
        .collect();
    let mx = Law::Maximum.combine(&ps).unwrap();
    let ml = Law::Multiplicative.combine(&ps).unwrap();
    let ad = Law::Additive.combine(&ps).unwrap();
    let gm = Law::GeometricMean.combine(&ps).unwrap();
    assert!(mx < ml && ml < ad, "ordering violated: {mx} {ml} {ad}");
    assert!(gm < ml, "geometric mean should sit below multiplicative");
}

/// Thm 4.6: convergence is decided by summability, and the divergent case
/// follows the exact closed form 1/(n+1) that the Python suite checks.
#[test]
fn convergence_closed_form_matches_python() {
    for n in [1000usize, 10_000, 100_000] {
        let mut logp = 0.0f64;
        for i in 0..n {
            logp += (1.0 - 1.0 / (i as f64 + 2.0)).ln();
        }
        let observed = logp.exp();
        let predicted = 1.0 / (n as f64 + 1.0);
        let rel = ((observed - predicted) / predicted).abs();
        assert!(rel < 1e-6, "n={n}: {observed:e} vs {predicted:e}");
    }

    // summable: stabilises at a strictly positive limit (Python: 0.2887880950866024)
    let mut logp = 0.0f64;
    for i in 0..2000 {
        logp += (1.0 - 2f64.powi(-(i + 1))).ln();
    }
    assert!((logp.exp() - 0.2887880950866024).abs() < 1e-9);
}

/// Thm 7.3 and the Mekaneck validation: on this substrate family the
/// threshold rule resolves while closure declines.
#[test]
fn closure_beats_threshold_as_in_python() {
    let reg = [
        Catalyst { name: "spectral".into(), reaches: "cellA".into() },
        Catalyst { name: "surrogate".into(), reaches: "cellA".into() },
        Catalyst { name: "phase".into(), reaches: "cellB".into() },
    ];
    let unc = |c: &str| if c == "cellA" { 5.0 } else { 40.0 };

    let thr = run_to_threshold(&reg, &unc, 10.0).unwrap();
    let clo = run_to_closure(&reg).unwrap();

    // Python: threshold_invocations = 1, closure_invocations = 2
    assert_eq!(thr.record, 1);
    assert_eq!(clo.record, 2);
    assert!(thr.outcome.is_resolved());
    assert_eq!(
        clo.outcome,
        Outcome::Declined { cells: vec!["cellA".into(), "cellB".into()] }
    );
}

/// The falsifiability asymmetry between the two floor estimators
/// (Rem 3.5), which the Python suite reports in both sampling regimes.
#[test]
fn floor_estimators_differ_in_kind() {
    fn stages(beta: f64, seed: u64) -> ExpandingFamily {
        let mut s = seed;
        let mut f = ExpandingFamily::new();
        for n in [50usize, 120, 400, 1000, 2500, 4000] {
            let obs = (0..n)
                .map(|_| {
                    s = s.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
                    let u = ((s >> 11) as f64) / ((1u64 << 53) as f64);
                    beta + 40.0 * u.powi(3)
                })
                .collect();
            f.push_stage(obs).unwrap();
        }
        f
    }

    // floored: both recover it, and only the asymptotic one supports the claim
    let f10 = stages(10.0, 11);
    let a = f10.estimate(FloorEstimator::Asymptotic).unwrap();
    let m = f10.estimate(FloorEstimator::SampleMinimum).unwrap();
    assert!((a.value - 10.0).abs() < 0.5);
    assert!(m.value >= 10.0, "sample minimum is biased upward");
    assert!(a.supports_positive_floor(ZERO_TOLERANCE));
    assert!(!m.supports_positive_floor(ZERO_TOLERANCE));

    // floorless: the sample minimum is still strictly positive, and so
    // reports nothing; the asymptotic estimate does not support a floor
    let f0 = stages(0.0, 11);
    let a0 = f0.estimate(FloorEstimator::Asymptotic).unwrap();
    let m0 = f0.estimate(FloorEstimator::SampleMinimum).unwrap();
    assert!(m0.value > 0.0, "sample minimum can never be non-positive");
    assert!(!a0.supports_positive_floor(ZERO_TOLERANCE));
}

/// Prop 6.2: η flags a binding whose event types do not discriminate.
#[test]
fn separation_flags_an_uninformative_binding() {
    let separated = generate(200, &[("A", 0.55), ("B", 0.30), ("C", 0.08)], 0.02, 3);
    let compressed = generate(200, &[("A", 0.300), ("B", 0.302), ("C", 0.299)], 0.12, 3);

    let s1 = separation(&separated).unwrap();
    let s2 = separation(&compressed).unwrap();
    assert!(s1.eta > s2.eta, "separated {} vs compressed {}", s1.eta, s2.eta);
    assert!(!s2.is_informative(), "compressed eta = {}", s2.eta);
}
