/**
 * The TypeScript half of the shared diagnostic suite.
 *
 * `fixtures.json` is generated by the Rust:
 *
 *     cargo test -p mekaneck-lang --test fixtures -- --ignored
 *
 * Both implementations are checked against it, so a divergence between the
 * editor and the binary fails on both sides rather than shipping as a
 * diagnostic that disagrees with the compiler.
 */

import { describe, expect, it } from "vitest";

import { diagnose } from "./checker";
import fixtures from "./fixtures.json";

interface ExpectedDiagnostic {
  severity: string;
  line: number;
  column: number;
  message_contains: string;
}

interface Case {
  name: string;
  rationale: string;
  source: string;
  floors: Record<string, number>;
  expected: ExpectedDiagnostic[];
}

const cases = fixtures as unknown as Case[];

describe("mekaneck diagnostics match the Rust", () => {
  it("has fixtures to check", () => {
    expect(cases.length).toBeGreaterThan(0);
  });

  for (const c of cases) {
    it(`${c.name}`, () => {
      const got = diagnose(c.source, c.floors);

      expect(
        got.map((d) => `${d.severity} ${d.line}:${d.column} ${d.message}`),
        `${c.name}: wrong number of diagnostics\nrationale: ${c.rationale}`,
      ).toHaveLength(c.expected.length);

      got.forEach((g, i) => {
        const e = c.expected[i];
        expect(g.severity, `${c.name}: severity`).toBe(e.severity);
        expect(g.line, `${c.name}: line`).toBe(e.line);
        expect(g.column, `${c.name}: column`).toBe(e.column);
        expect(
          g.message.toLowerCase(),
          `${c.name}: message should mention "${e.message_contains}"`,
        ).toContain(e.message_contains);
      });
    });
  }
});

describe("the two commitments the language enforces", () => {
  const substrate =
    "substrate Osc { receivers : r(); observable : o(); events : e(); floor : asymptotic(); }";
  const triad = [
    "catalyst a : f() independent b, c;",
    "catalyst b : g() independent a, c;",
    "catalyst c : h() independent a, b;",
  ].join("\n");

  it("rejects a seek with no exclusion clause", () => {
    const src = `${substrate}\n${triad}\nlet x = seek t() via (a, b, c) until closure;\nreport x;`;
    const d = diagnose(src, { Osc: 12.5 });
    expect(d).toHaveLength(1);
    expect(d[0].severity).toBe("error");
    expect(d[0].message).toContain("excluding");
  });

  it("rejects fewer than three mutually independent catalysts", () => {
    const src = `${substrate}\n${triad}\nlet x = seek t() excluding rest() via (a, b) until closure;\nreport x;`;
    const d = diagnose(src, { Osc: 12.5 });
    expect(d[0].message).toContain("at least 3");
  });

  it("accepts a seek with no via clause at all", () => {
    // T-Seek-Coh constrains what is named, not that anything is.
    const src = `${substrate}\nlet x = seek t() excluding rest() until closure;\nreport x;`;
    expect(diagnose(src, { Osc: 12.5 })).toHaveLength(0);
  });

  it("treats an absent floor as a warning, not an error", () => {
    const src = `${substrate}\n${triad}\nlet x = seek t() excluding rest() via (a, b, c) until closure;\nreport x;`;
    const d = diagnose(src, {});
    expect(d).toHaveLength(1);
    expect(d[0].severity).toBe("warning");
  });
});
